# Generated by Django 3.0.5 on 2020-08-30 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policeInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaseName', models.CharField(max_length=255)),
                ('CaseDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CaseAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaseAccepted', models.BooleanField(default=False)),
                ('CaseCompleted', models.BooleanField(default=False)),
                ('AssignedCase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CaseID', to='policeInfo.CaseInfo')),
                ('AssignedTo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PoliceID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
