# Generated by Django 3.0.5 on 2020-09-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policeInfo', '0002_caseassign_caseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseinfo',
            name='CreatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
